#!/usr/bin/env python3
import argparse
import json
from pathlib import Path


ALLOC_PAD_RADIUS = 4
FLOAT_BYTES = 4
RTX5090_MEMORY_BYTES = 32 * 1024 ** 3


def read_key_value(path):
    values = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def read_input_values(path):
    lines = [
        line.strip()
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines()
        if line.strip() != ""
    ]
    values = {}
    if len(lines) >= 34:
        values.update(
            {
                "trace_count": lines[12],
                "nt": lines[18],
                "ny": lines[22],
                "nx": lines[23],
                "nz": lines[24],
                "dy": lines[25],
                "dx": lines[26],
                "dz": lines[27],
                "npml": lines[28],
                "xpad": lines[30],
                "gpu_count": lines[33],
            }
        )
    return values


def to_int(values, key, default=0):
    try:
        return int(float(values.get(key, default)))
    except (TypeError, ValueError):
        return default


def find_input(case_dir, manifest):
    if "input" in manifest:
        path = case_dir / manifest["input"]
        if path.exists():
            return path
    inputs = sorted(case_dir.glob("input*.in"))
    return inputs[0] if inputs else None


def estimate_case(case_dir):
    manifest = read_key_value(case_dir / "case_manifest.txt")
    input_path = find_input(case_dir, manifest)
    input_values = read_input_values(input_path) if input_path else {}
    values = {**input_values, **manifest}

    ny = to_int(values, "ny")
    nx = to_int(values, "nx")
    nz = to_int(values, "nz")
    npml = to_int(values, "npml")
    nt = to_int(values, "nt")
    shots = to_int(values, "shots", 1)
    gpu_count = to_int(values, "gpu_count", 1)
    trace_count = to_int(values, "trace_count", 0)
    receivers_per_shot = to_int(values, "receivers_per_shot", trace_count)

    nby = ny + 2 * (npml + ALLOC_PAD_RADIUS)
    nbx = nx + 2 * (npml + ALLOC_PAD_RADIUS)
    nbz = nz + 2 * (npml + ALLOC_PAD_RADIUS)
    points = nby * nbx * nbz
    bytes_per_pressure = points * FLOAT_BYTES
    current_pressure_bytes = 2 * bytes_per_pressure
    triple_pressure_bytes = 3 * bytes_per_pressure
    additional_bytes = bytes_per_pressure
    active_rank_fraction = triple_pressure_bytes / RTX5090_MEMORY_BYTES

    return {
        "case": case_dir.name,
        "path": case_dir.as_posix(),
        "input": input_path.as_posix() if input_path else None,
        "ny": ny,
        "nx": nx,
        "nz": nz,
        "npml": npml,
        "nt": nt,
        "shots": shots,
        "gpu_count": gpu_count,
        "trace_count": trace_count,
        "receivers_per_shot": receivers_per_shot,
        "nby_pad": nby,
        "nbx_pad": nbx,
        "nbz_pad": nbz,
        "pressure_points": points,
        "bytes_per_pressure": bytes_per_pressure,
        "current_pressure_bytes": current_pressure_bytes,
        "triple_pressure_bytes": triple_pressure_bytes,
        "additional_bytes": additional_bytes,
        "bytes_per_pressure_gib": bytes_per_pressure / 1024 ** 3,
        "current_pressure_gib": current_pressure_bytes / 1024 ** 3,
        "triple_pressure_gib": triple_pressure_bytes / 1024 ** 3,
        "additional_gib": additional_bytes / 1024 ** 3,
        "triple_fraction_of_32gb": active_rank_fraction,
        "rtx5090_pressure_margin_ok": active_rank_fraction < 0.25,
        "note": "Estimate is per active rank/shot; this code allocates pressure buffers inside fd_3d_f per shot call.",
    }


def markdown_report(results):
    largest = max(results, key=lambda item: item["triple_pressure_bytes"]) if results else None
    lines = [
        "# Pressure Triple-Buffer Memory Estimate",
        "",
        "Generated by `tools/pressure_buffer_memory_estimate.py`.",
        "",
        "Assumptions:",
        "",
        "- Pressure allocation uses `ny/nx/nz + 2*(npml + radius)` in each dimension.",
        "- Allocation pad `radius = 4` from `include/inc3D/cu_common.h`.",
        "- Pressure values are `float`, 4 bytes.",
        "- Current code uses 2 pressure buffers; triple-buffer design uses 3.",
        "- Estimates are per active MPI rank / active shot call, not total shots multiplied.",
        "- RTX 5090 memory reference is 32 GiB.",
        "",
        "| Case | Model | npml | nt | shots | padded `(y,x,z)` | pressure pts | 2 buffers GiB | 3 buffers GiB | add GiB | 3buf / 32GiB | OK |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for item in results:
        lines.append(
            "| {case} | {ny}x{nx}x{nz} | {npml} | {nt} | {shots} | "
            "{nby_pad}x{nbx_pad}x{nbz_pad} | {pressure_points} | "
            "{current_pressure_gib:.4f} | {triple_pressure_gib:.4f} | "
            "{additional_gib:.4f} | {triple_fraction_of_32gb:.4f} | {rtx5090_pressure_margin_ok} |".format(
                **item
            )
        )
    lines.extend(
        [
            "",
            "## Conclusion",
            "",
            "For the current benchmark cases, the extra pressure buffer is modest relative to 32 GiB RTX 5090 memory.",
            (
                "The largest tracked case is `{case}` and uses about `{triple_pressure_gib:.4f} GiB` "
                "for three pressure buffers, adding about `{additional_gib:.4f} GiB` over the current two-buffer scheme."
            ).format(**largest) if largest else "No benchmark cases were found.",
            "",
            "This memory estimate does not include velocity fields, PML memory arrays, receiver output, velocity model, or MPI/runtime overhead.",
            "It only answers whether the additional pressure array itself is plausible.",
        ]
    )
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--cases-root", default="benchmarks/cases")
    parser.add_argument(
        "--case",
        action="append",
        default=None,
        help="Restrict to a case name. Can be passed multiple times.",
    )
    parser.add_argument("--json-out", default=None)
    parser.add_argument("--markdown-out", default=None)
    args = parser.parse_args()

    cases_root = Path(args.cases_root)
    if args.case:
        case_dirs = [cases_root / name for name in args.case]
    else:
        case_dirs = sorted(
            path for path in cases_root.iterdir()
            if path.is_dir() and ((path / "case_manifest.txt").exists() or list(path.glob("input*.in")))
        )
    results = [estimate_case(path) for path in case_dirs]
    report = {
        "alloc_pad_radius": ALLOC_PAD_RADIUS,
        "float_bytes": FLOAT_BYTES,
        "rtx5090_memory_bytes": RTX5090_MEMORY_BYTES,
        "results": results,
    }

    if args.json_out:
        out = Path(args.json_out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(report, indent=2), encoding="utf-8")
    if args.markdown_out:
        out = Path(args.markdown_out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(markdown_report(results), encoding="utf-8")

    print("case ny nx nz npml nt shots padded_y padded_x padded_z pressure_points current_GiB triple_GiB add_GiB ok")
    for item in results:
        print(
            "{case} {ny} {nx} {nz} {npml} {nt} {shots} {nby_pad} {nbx_pad} {nbz_pad} "
            "{pressure_points} {current_pressure_gib:.4f} {triple_pressure_gib:.4f} "
            "{additional_gib:.4f} {rtx5090_pressure_margin_ok}".format(**item)
        )


if __name__ == "__main__":
    main()
